name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        issue-message: 'Hey, congratulations!! 🎉 for creating your first issue. \n Wait for the admin approval now and then you can go ahead to solve the issue. \n Do give a star ⭐ if you like this project. '
        pr-message: 'Congratulations!! 🎉 for making your first PR. \n Admin will review the changes soon and merge finally.😊 \n Do give a star ⭐ if you like this project. '